kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ui-anonymous
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/proxy
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-anonymous-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ui-anonymous
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
