- name: Install keepalived on Centos server
  yum: name={{ item }} state=latest
  with_items:
  - keepalived
  when: ansible_distribution == "CentOS"

- name: Install keepalived on Ubuntu server
  apt: name={{ item }} state=latest
  with_items:
  - keepalived
  when: ansible_distribution == "Ubuntu"


- name: Modify keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Restart keepalived
  shell: systemctl daemon-reload && systemctl enable keepalived && systemctl restart keepalived
