- name: Create yaml folder
  file: name={{ yaml_dir }} state=directory

- name: Create yaml filses
  template: src={{ item }} dest={{ yaml_dir }}/{{ item }}
  with_items:
  - helm-rbac.yaml
  - ingress.yaml
  - kubernetes-dashboard.yaml
  - nginx-ingress-controller.yaml
  - ui-rbac.yaml

- name: Set up RBAC for dashboard
  raw: kubectl get clusterrole|grep ui || kubectl create -f {{ yaml_dir }}/ui-rbac.yaml
                    
- name: Install kubernetes-dashboard 
  raw:  kubectl get po -n kube-system|grep dashboard || kubectl create -f /root/.kube/kube-apps/kubernetes-dashboard.yaml
                                
- name: Install ingress-controller
  raw: kubectl get po -n kube-system|grep ingress || kubectl create -f /root/.kube/kube-apps/nginx-ingress-controller.yaml
                        
- name: Install ingress
  raw: kubectl get ing |grep ingress || kubectl create -f /root/.kube/kube-apps/ingress.yaml
                  
- name: Set up helm RBAC
  raw: kubectl get sa -n kube-system|grep tiller || kubectl create -f /root/.kube/kube-apps/helm-rbac.yaml
           
- name: Copy helm executable
  copy: src={{ base_dir }}/bin/helm/{{ helm_version }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - helm
         
- name: Init helm
  raw: kubectl get po -n kube-system|grep helm || helm init  --service-account tiller --tiller-namespace kube-system
